package com.sdtech.demo.model;


import com.sdtech.demo.model.base.BaseBaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseDict extends BaseBaseDict<BaseDict> {
	public static final BaseDict dao = new BaseDict().dao();
}
