package com.sdtech.demo.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseDict<M extends BaseBaseDict<M>> extends Model<M> implements IBean {

	public void setDictId(Long dictId) {
		set("dict_id", dictId);
	}

	public Long getDictId() {
		return getLong("dict_id");
	}

	public void setParentsId(Integer parentsId) {
		set("parents_id", parentsId);
	}

	public Integer getParentsId() {
		return getInt("parents_id");
	}

	public void setDictKey(String dictKey) {
		set("dict_key", dictKey);
	}

	public String getDictKey() {
		return getStr("dict_key");
	}

	public void setDictKeyInfo(String dictKeyInfo) {
		set("dict_key_info", dictKeyInfo);
	}

	public String getDictKeyInfo() {
		return getStr("dict_key_info");
	}

	public void setDictVal(String dictVal) {
		set("dict_val", dictVal);
	}

	public String getDictVal() {
		return getStr("dict_val");
	}

	public void setDictValInfo(String dictValInfo) {
		set("dict_val_info", dictValInfo);
	}

	public String getDictValInfo() {
		return getStr("dict_val_info");
	}

	public void setIsSys(Integer isSys) {
		set("is_sys", isSys);
	}

	public Integer getIsSys() {
		return getInt("is_sys");
	}

	public void setCreateBy(Integer createBy) {
		set("create_by", createBy);
	}

	public Integer getCreateBy() {
		return getInt("create_by");
	}

	public void setCreateDt(java.util.Date createDt) {
		set("create_dt", createDt);
	}

	public java.util.Date getCreateDt() {
		return get("create_dt");
	}

	public void setUpdateBy(Integer updateBy) {
		set("update_by", updateBy);
	}

	public Integer getUpdateBy() {
		return getInt("update_by");
	}

	public void setUpdateDt(java.util.Date updateDt) {
		set("update_dt", updateDt);
	}

	public java.util.Date getUpdateDt() {
		return get("update_dt");
	}

	public void setIsDel(Integer isDel) {
		set("is_del", isDel);
	}

	public Integer getIsDel() {
		return getInt("is_del");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return getStr("remark");
	}

}
